verion: 2.0
jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/sdk
        steps:
            - checkout
            - run:
                name: Restore packages
                command: dotnet restore ~/src/GardenHub.sln
            - run:
                name: Build GardenHub
                command: dotnet Build ~/src/GardenHub.sln --no-restore
            - run:
                name: Run Tests
                command: fotnet test ~/src/GardenHub.Tests.sln --no-restore